name: flow-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20230802.0
  - alembic=1.8.1
  - appdirs=1.4.4
  - appnope=0.1.2
  - arrow-cpp=14.0.2
  - asn1crypto=1.5.1
  - asttokens=2.0.5
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - backcall=0.2.0
  - blas=2.121
  - blas-devel=3.9.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - comm=0.1.2
  - cryptography=42.0.2
  - cycler=0.11.0
  - databricks-cli=0.17.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - distlib=0.3.6
  - docker-py=4.4.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.13.1
  - flask=2.2.5
  - fonttools=4.25.0
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.37
  - glog=0.5.0
  - gorilla=0.4.0
  - greenlet=3.0.1
  - grpc-cpp=1.48.2
  - gtest=1.14.0
  - gunicorn=20.1.0
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - ipykernel=6.25.0
  - ipython=8.15.0
  - itsdangerous=2.0.1
  - jedi=0.18.1
  - jinja2=3.1.3
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.26
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - mako=1.2.3
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mlflow=2.10.2
  - mlflow-skinny=2.10.2
  - mlflow-ui=2.10.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - openblas=0.3.26
  - openjpeg=2.3.0
  - openssl=3.2.1
  - orc=1.7.4
  - packaging=23.1
  - pandas=1.5.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prometheus_flask_exporter=0.22.4
  - prompt-toolkit=3.0.43
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - querystring_parser=1.2.4
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - setuptools=68.2.2
  - simplejson=3.17.6
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.10
  - sqlalchemy=2.0.25
  - sqlite=3.41.2
  - sqlparse=0.4.4
  - stack_data=0.2.0
  - tabulate=0.9.0
  - threadpoolctl=2.2.0
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.1.0
  - utf8proc=2.6.1
  - virtualenv=20.17.1
  - wcwidth=0.2.5
  - websocket-client=0.58.0
  - werkzeug=2.3.8
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
